# Generated by Django 4.1.1 on 2022-10-08 14:56

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PVData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_type', models.CharField(max_length=50, verbose_name='tipo de módulo')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='referencia')),
                ('comments', models.TextField(blank=True, max_length=50, verbose_name='referencia')),
                ('temperature', models.SmallIntegerField(null=True, verbose_name='temperatura')),
                ('measure_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de medición')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('current_data', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=list, size=None)),
                ('voltage_data', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=list, size=None)),
                ('power_data', django.contrib.postgres.fields.ArrayField(base_field=models.SmallIntegerField(), default=list, size=None)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'PV Data',
                'verbose_name_plural': 'PV Data',
            },
        ),
    ]
