# Generated by Django 4.1.1 on 2022-10-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('I', 'Intersexual'), ('N', 'No response')], max_length=11, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='user',
            name='legal_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='legal ID'),
        ),
    ]
